//
//  TokenIcon.swift
//  FreeOTP
//
//  Created by Justin Stephenson on 2/12/20.
//  Copyright © 2020 Fedora Project. All rights reserved.
//

import Foundation
import UIKit

public extension UIColor {
    convenience init(hexString: String, alpha: CGFloat = 1.0) {
        let hexString: String = hexString.trimmingCharacters(in: CharacterSet.whitespacesAndNewlines)
        let scanner = Scanner(string: hexString)

        if (hexString.hasPrefix("#")) {
            scanner.scanLocation = 1
        }

        var color: UInt32 = 0
        scanner.scanHexInt32(&color)

        let mask = 0x000000FF
        let r = Int(color >> 16) & mask
        let g = Int(color >> 8) & mask
        let b = Int(color) & mask

        let red   = CGFloat(r) / 255.0
        let green = CGFloat(g) / 255.0
        let blue  = CGFloat(b) / 255.0

        self.init(red:red, green:green, blue:blue, alpha:alpha)
    }
}

extension UIImage {
    func addImagePadding(x: CGFloat, y: CGFloat) -> UIImage? {
        let width: CGFloat = size.width + x
        let height: CGFloat = size.height + y
        UIGraphicsBeginImageContextWithOptions(CGSize(width: width, height: height), false, 0)
        let origin: CGPoint = CGPoint(x: (width - size.width) / 2, y: (height - size.height) / 2)
        draw(at: origin)
        let imageWithPadding = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()

        return imageWithPadding
    }
}

/* Taken from https://github.com/thii/FontAwesome.swift/blob/master/Sources/FontAwesome/FontAwesome.swift */
public extension UIImage {
    static func fontAwesomeIcon(faName: String, faType: faIconType, textColor: UIColor = .white, size: CGSize = CGSize(width: 30, height: 30), backgroundColor: UIColor = UIColor.clear, borderWidth: CGFloat = 0, borderColor: UIColor = UIColor.clear) -> UIImage {

        // Prevent application crash when passing size where width or height is set equal to or less than zero, by clipping width and height to a minimum of 1 pixel.
        var size = size
        if size.width <= 0 { size.width = 1 }
        if size.height <= 0 { size.height = 1 }

        let paragraph = NSMutableParagraphStyle()
        paragraph.alignment = NSTextAlignment.center

        // Taken from FontAwesome.io's Fixed Width Icon CSS.
        let fontAspectRatio: CGFloat = 1.28571429
        let fontSize = min(size.width / fontAspectRatio, size.height)

        // stroke width expects a whole number percentage of the font size
        let strokeWidth: CGFloat = fontSize == 0 ? 0 : (-100 * 0 / fontSize)

        var iconStr = ""
        var fontName = ""

        switch faType {
        case .brands:
            iconStr = faIconsBrands[faName] ?? ""
            fontName = "FontAwesome6Brands-Regular"
            break
        case .solid:
            iconStr = faIconsSolid[faName] ?? ""
            fontName = "FontAwesome6Free-Solid"
            break
        default:
            // Type not supported
            break
        }

        let attributedString = NSAttributedString(string: iconStr, attributes: [
            NSAttributedString.Key.font: UIFont(name: fontName, size: fontSize)!,
            NSAttributedString.Key.foregroundColor: UIColor.white,
            NSAttributedString.Key.backgroundColor: UIColor.clear,
            NSAttributedString.Key.paragraphStyle: paragraph,
            NSAttributedString.Key.strokeWidth: strokeWidth,
            NSAttributedString.Key.strokeColor: UIColor.clear
        ])

        UIGraphicsBeginImageContextWithOptions(size, false, 0.0)
        attributedString.draw(in: CGRect(x: 0, y: (size.height - fontSize) / 2, width: size.width, height: fontSize))
        let image = UIGraphicsGetImageFromCurrentImageContext()
        UIGraphicsEndImageContext()
        return image!
    }
}

public struct IconData {
    public var iconImg: UIImage! = nil
    public var bgColor: String = ""
    public var name: String = ""
}

public struct IconMatch {
    var name: String
    var levDist: Int
}

public enum faIconType {
    case brands
    case solid
    case recommended
}

public class TokenIcon {
    let defaults = UserDefaults.standard

    public init() {}

    public let iconsBrand = Array(faIconsBrands.keys)
    public let iconsSolid = Array(faIconsSolid.keys)

    public func saveMapping(issuer: String, iconName: String, iconColor: String) {
        let iconDict = ["Name": iconName, "Color": iconColor]
        defaults.set(iconDict, forKey: issuer)
    }

    public func loadMapping(issuer: String) -> [String: String]? {
        guard let iconName = defaults.object(forKey: issuer) as? [String: String] else {
            return nil
        }
        return iconName
    }

    public func faIconExists(for iconName: String) -> (type: faIconType, name: String)!  {
        /* Drop any 'fa-' prefix from legacy FontAwesome library usage */
        let updated = iconName.lowercased().replacingOccurrences(of: "fa-", with: "")

        /* Use liberal search heuristics to handle names like 'Red Hat' or 'GitHub' */
        let newName = updated.lowercased().replacingOccurrences(of: " ", with: "")

        if !updated.isEmpty {
            /* Returns the type and updated string to the caller */
            if (faIconsBrands.keys.contains(newName)) {
                return (.brands, newName)
            } else if (faIconsSolid.keys.contains(newName)) {
                return (.solid, newName)
            }
        }
        return nil
    }

    public func getBrandColor(_ key: String) -> UIColor! {
        let brand = key.replacingOccurrences(of: " ", with: "")
        if let val = iconBGColorMapping[brand] {
            return UIColor(hexString: val)
        }

        return nil
    }

    public func getBrandColorHex(_ key: String) -> String! {
        let brand = key.replacingOccurrences(of: " ", with: "")
        if let val = iconBGColorMapping[brand] {
            return val
        }

        return nil
    }

    public func getBackgroundColor(name: String, uriColor: String = "") -> UIColor {
        // Use URI-provided color
        if uriColor != "" {
            return UIColor(hexString: uriColor)
        }
        // Use color from brand dictionary
        if let color = getBrandColor(name) {
            return color
        }
        // Fallback to predictable hash-based color
        return name == "" ? UIColor.systemGray : getBackgroundColorHash(name)
    }

    func sha256(data : Data) -> Data {
        var hash = [UInt8](repeating: 0,  count: Int(CC_SHA256_DIGEST_LENGTH))
        data.withUnsafeBytes {
            _ = CC_SHA256($0.baseAddress, CC_LONG(data.count), &hash)
        }
        return Data(hash)
    }

    public func getBackgroundColorHash(_ issuer: String) -> UIColor {
        let mydata = sha256(data: Data(issuer.utf8))
        let number = mydata.withUnsafeBytes( {
            $0.load(as: Int.self )
        })
        let idx = abs(number)
        let index = idx % backgroundColors.count
        return UIColor(hexString: backgroundColors[index])
    }

    public func getCustomIcon(issuer: String, size: CGSize =  CGSize(width: 30, height: 30)) -> IconData! {
        var icon = IconData()
        if let faName = issuerBrandMapping[issuer] {
            icon.iconImg = UIImage.fontAwesomeIcon(faName: faName, faType: .brands, size: size)
            icon.name = faName
            let color = iconBGColorMapping[faName]
            icon.bgColor = color ?? "#6F7171"
            return icon
        }

        if issuer.isEmpty {
            return nil
        }

        if let iconMapping = loadMapping(issuer: issuer) {
            if let faIcon = faIconExists(for: iconMapping["Name"]!) {
                icon.iconImg = UIImage.fontAwesomeIcon(faName: faIcon.name, faType: faIcon.type, size: size)
                icon.bgColor = iconMapping["Color"] ?? "#6F7171"
                icon.name = faIcon.name

                return icon
            }
        }
        return nil
    }

    public func getSuggestions(urlc: URLComponents, levDistMax: Int = 4, numSuggestions: Int = 3) -> [IconMatch] {
        var suggestedIcons = [IconMatch]()
        let URI = URIParameters()

        if let label = URI.getLabel(from: urlc) {
            for icon in faIconsBrands {
                let levDist = levDis(label.issuer, icon.key)
                if levDist < levDistMax {
                    let icon = IconMatch(name: icon.key, levDist: levDist)
                    suggestedIcons.append(icon)
                }
            }
        }

        suggestedIcons.sort { $0.levDist < $1.levDist }

        let remove = suggestedIcons.count - numSuggestions
        if remove > 0 {
            suggestedIcons.removeLast(remove)
        }

        return suggestedIcons
    }

    func levDis(_ w1: String, _ w2: String) -> Int {
        let empty = [Int](repeating:0, count: w2.count)
        var last = [Int](0...w2.count)

        for (i, char1) in w1.enumerated() {
            var cur = [i + 1] + empty
            for (j, char2) in w2.enumerated() {
                cur[j + 1] = char1 == char2 ? last[j] : Swift.min(last[j], last[j + 1], cur[j]) + 1
            }
            last = cur
        }
        return last.last!
    }

    let iconBGColorMapping = [
        "bitbucket": "#0747A6",
        "fa-bitbucket": "#0747A6",
        "facebook": "#3B5998",
        "fa-facebook": "#3B5998",
        "github": "#24292E",
        "fa-github": "#24292E",
        "gitlab": "#292961",
        "fa-gitlab": "#292961",
        "reddit": "#FF4500",
        "fa-reddit": "#FF4500",
        "redhat": "#FF0000",
        "fa-redhat": "#FF0000",
        "steam": "#242424",
        "fa-steam": "#242424",
    ]

    //  Android material design colors https:gist.github.com/daniellevass/b0b8cfa773488e138037
    let backgroundColors = [
        "#F44336",          // md_red_500
        "#673AB7",          // md_deep_purple_500
        "#03A9F4",          // md_light_blue_500
        "#4CAF50",          // md_green_500
        "#FF5722",          // md_deep_orange_500
        "#E91E63",          // md_pink_500
        "#3F51B5",          // md_indigo_500
        "#00BCD4",          // md_cyan_500
        "#8BC34A",          // md_light_green_500
        "#FFC107",          // md_amber_500
        "#795548",          // md_brown_500
        "#9C27B0",          // md_purple_500
        "#2196F3",          // md_blue_500
        "#009688",          // md_teal_500
        "#CDDC39",          // md_lime_500
        "#FF9800",          // md_orange_500
    ]

    let issuerBrandMapping = [
        "gitlab.com": "fa-gitlab"
    ]

}


// Lowercase all keys for simplicity
let faIconsBrands = [
    "fa500px": "\u{f26e}",
    "accessibleIcon": "\u{f368}",
    "accusoft": "\u{f369}",
    "acquisitionsIncorporated": "\u{f6af}",
    "adn": "\u{f170}",
    "adversal": "\u{f36a}",
    "affiliatetheme": "\u{f36b}",
    "airbnb": "\u{f834}",
    "algolia": "\u{f36c}",
    "alipay": "\u{f642}",
    "amazon": "\u{f270}",
    "amazonPay": "\u{f42c}",
    "amilia": "\u{f36d}",
    "android": "\u{f17b}",
    "angellist": "\u{f209}",
    "angrycreative": "\u{f36e}",
    "angular": "\u{f420}",
    "appStore": "\u{f36f}",
    "appStoreIos": "\u{f370}",
    "apper": "\u{f371}",
    "apple": "\u{f179}",
    "applePay": "\u{f415}",
    "artstation": "\u{f77a}",
    "asymmetrik": "\u{f372}",
    "atlassian": "\u{f77b}",
    "audible": "\u{f373}",
    "autoprefixer": "\u{f41c}",
    "avianex": "\u{f374}",
    "aviato": "\u{f421}",
    "aws": "\u{f375}",
    "bandcamp": "\u{f2d5}",
    "battleNet": "\u{f835}",
    "behance": "\u{f1b4}",
    "behanceSquare": "\u{f1b5}",
    "bimobject": "\u{f378}",
    "bitbucket": "\u{f171}",
    "bitcoin": "\u{f379}",
    "bity": "\u{f37a}",
    "blackTie": "\u{f27e}",
    "blackberry": "\u{f37b}",
    "blogger": "\u{f37c}",
    "bloggerB": "\u{f37d}",
    "bluetooth": "\u{f293}",
    "bluetoothB": "\u{f294}",
    "bootstrap": "\u{f836}",
    "btc": "\u{f15a}",
    "buffer": "\u{f837}",
    "buromobelexperte": "\u{f37f}",
    "buyNLarge": "\u{f8a6}",
    "buysellads": "\u{f20d}",
    "canadianMapleLeaf": "\u{f785}",
    "ccAmazonPay": "\u{f42d}",
    "ccAmex": "\u{f1f3}",
    "ccApplePay": "\u{f416}",
    "ccDinersClub": "\u{f24c}",
    "ccDiscover": "\u{f1f2}",
    "ccJcb": "\u{f24b}",
    "ccMastercard": "\u{f1f1}",
    "ccPaypal": "\u{f1f4}",
    "ccStripe": "\u{f1f5}",
    "ccVisa": "\u{f1f0}",
    "centercode": "\u{f380}",
    "centos": "\u{f789}",
    "chrome": "\u{f268}",
    "chromecast": "\u{f838}",
    "cloudflare": "\u{e07d}",
    "cloudscale": "\u{f383}",
    "cloudsmith": "\u{f384}",
    "cloudversify": "\u{f385}",
    "codepen": "\u{f1cb}",
    "codiepie": "\u{f284}",
    "confluence": "\u{f78d}",
    "connectdevelop": "\u{f20e}",
    "contao": "\u{f26d}",
    "cottonBureau": "\u{f89e}",
    "cpanel": "\u{f388}",
    "creativeCommons": "\u{f25e}",
    "creativeCommonsBy": "\u{f4e7}",
    "creativeCommonsNc": "\u{f4e8}",
    "creativeCommonsNcEu": "\u{f4e9}",
    "creativeCommonsNcJp": "\u{f4ea}",
    "creativeCommonsNd": "\u{f4eb}",
    "creativeCommonsPd": "\u{f4ec}",
    "creativeCommonsPdAlt": "\u{f4ed}",
    "creativeCommonsRemix": "\u{f4ee}",
    "creativeCommonsSa": "\u{f4ef}",
    "creativeCommonsSampling": "\u{f4f0}",
    "creativeCommonsSamplingPlus": "\u{f4f1}",
    "creativeCommonsShare": "\u{f4f2}",
    "creativeCommonsZero": "\u{f4f3}",
    "criticalRole": "\u{f6c9}",
    "css3": "\u{f13c}",
    "css3Alt": "\u{f38b}",
    "cuttlefish": "\u{f38c}",
    "dAndD": "\u{f38d}",
    "dAndDBeyond": "\u{f6ca}",
    "dailymotion": "\u{e052}",
    "dashcube": "\u{f210}",
    "deezer": "\u{e077}",
    "delicious": "\u{f1a5}",
    "deploydog": "\u{f38e}",
    "deskpro": "\u{f38f}",
    "dev": "\u{f6cc}",
    "deviantart": "\u{f1bd}",
    "dhl": "\u{f790}",
    "diaspora": "\u{f791}",
    "digg": "\u{f1a6}",
    "digitalOcean": "\u{f391}",
    "discord": "\u{f392}",
    "discourse": "\u{f393}",
    "dochub": "\u{f394}",
    "docker": "\u{f395}",
    "draft2digital": "\u{f396}",
    "dribbble": "\u{f17d}",
    "dribbbleSquare": "\u{f397}",
    "dropbox": "\u{f16b}",
    "drupal": "\u{f1a9}",
    "dyalog": "\u{f399}",
    "earlybirds": "\u{f39a}",
    "ebay": "\u{f4f4}",
    "edge": "\u{f282}",
    "edgeLegacy": "\u{e078}",
    "elementor": "\u{f430}",
    "ello": "\u{f5f1}",
    "ember": "\u{f423}",
    "empire": "\u{f1d1}",
    "envira": "\u{f299}",
    "erlang": "\u{f39d}",
    "ethereum": "\u{f42e}",
    "etsy": "\u{f2d7}",
    "evernote": "\u{f839}",
    "expeditedssl": "\u{f23e}",
    "facebook": "\u{f09a}",
    "facebookF": "\u{f39e}",
    "facebookMessenger": "\u{f39f}",
    "facebookSquare": "\u{f082}",
    "fantasyFlightGames": "\u{f6dc}",
    "fedex": "\u{f797}",
    "fedora": "\u{f798}",
    "figma": "\u{f799}",
    "firefox": "\u{f269}",
    "firefoxBrowser": "\u{e007}",
    "firstOrder": "\u{f2b0}",
    "firstOrderAlt": "\u{f50a}",
    "firstdraft": "\u{f3a1}",
    "flickr": "\u{f16e}",
    "flipboard": "\u{f44d}",
    "fly": "\u{f417}",
    "fontAwesome": "\u{f2b4}",
    "fontAwesomeAlt": "\u{f35c}",
    "fontAwesomeFlag": "\u{f425}",
    "fonticons": "\u{f280}",
    "fonticonsFi": "\u{f3a2}",
    "fortAwesome": "\u{f286}",
    "fortAwesomeAlt": "\u{f3a3}",
    "forumbee": "\u{f211}",
    "foursquare": "\u{f180}",
    "freeCodeCamp": "\u{f2c5}",
    "freebsd": "\u{f3a4}",
    "fulcrum": "\u{f50b}",
    "galacticRepublic": "\u{f50c}",
    "galacticSenate": "\u{f50d}",
    "getPocket": "\u{f265}",
    "gg": "\u{f260}",
    "ggCircle": "\u{f261}",
    "git": "\u{f1d3}",
    "gitAlt": "\u{f841}",
    "gitSquare": "\u{f1d2}",
    "github": "\u{f09b}",
    "githubAlt": "\u{f113}",
    "githubSquare": "\u{f092}",
    "gitkraken": "\u{f3a6}",
    "gitlab": "\u{f296}",
    "gitter": "\u{f426}",
    "glide": "\u{f2a5}",
    "glideG": "\u{f2a6}",
    "gofore": "\u{f3a7}",
    "goodreads": "\u{f3a8}",
    "goodreadsG": "\u{f3a9}",
    "google": "\u{f1a0}",
    "googleDrive": "\u{f3aa}",
    "googlePay": "\u{e079}",
    "googlePlay": "\u{f3ab}",
    "googlePlus": "\u{f2b3}",
    "googlePlusG": "\u{f0d5}",
    "googlePlusSquare": "\u{f0d4}",
    "googleWallet": "\u{f1ee}",
    "gratipay": "\u{f184}",
    "grav": "\u{f2d6}",
    "gripfire": "\u{f3ac}",
    "grunt": "\u{f3ad}",
    "guilded": "\u{e07e}",
    "gulp": "\u{f3ae}",
    "hackerNews": "\u{f1d4}",
    "hackerNewsSquare": "\u{f3af}",
    "hackerrank": "\u{f5f7}",
    "hips": "\u{f452}",
    "hireAHelper": "\u{f3b0}",
    "hive": "\u{e07f}",
    "hooli": "\u{f427}",
    "hornbill": "\u{f592}",
    "hotjar": "\u{f3b1}",
    "houzz": "\u{f27c}",
    "html5": "\u{f13b}",
    "hubspot": "\u{f3b2}",
    "ideal": "\u{e013}",
    "imdb": "\u{f2d8}",
    "innosoft": "\u{e080}",
    "instagram": "\u{f16d}",
    "instagramSquare": "\u{e055}",
    "instalod": "\u{e081}",
    "intercom": "\u{f7af}",
    "internetExplorer": "\u{f26b}",
    "invision": "\u{f7b0}",
    "ioxhost": "\u{f208}",
    "itchIo": "\u{f83a}",
    "itunes": "\u{f3b4}",
    "itunesNote": "\u{f3b5}",
    "java": "\u{f4e4}",
    "jediOrder": "\u{f50e}",
    "jenkins": "\u{f3b6}",
    "jira": "\u{f7b1}",
    "joget": "\u{f3b7}",
    "joomla": "\u{f1aa}",
    "js": "\u{f3b8}",
    "jsSquare": "\u{f3b9}",
    "jsfiddle": "\u{f1cc}",
    "kaggle": "\u{f5fa}",
    "keybase": "\u{f4f5}",
    "keycdn": "\u{f3ba}",
    "kickstarter": "\u{f3bb}",
    "kickstarterK": "\u{f3bc}",
    "korvue": "\u{f42f}",
    "laravel": "\u{f3bd}",
    "lastfm": "\u{f202}",
    "lastfmSquare": "\u{f203}",
    "leanpub": "\u{f212}",
    "less": "\u{f41d}",
    "line": "\u{f3c0}",
    "linkedin": "\u{f08c}",
    "linkedinIn": "\u{f0e1}",
    "linode": "\u{f2b8}",
    "linux": "\u{f17c}",
    "lyft": "\u{f3c3}",
    "magento": "\u{f3c4}",
    "mailchimp": "\u{f59e}",
    "mandalorian": "\u{f50f}",
    "markdown": "\u{f60f}",
    "mastodon": "\u{f4f6}",
    "maxcdn": "\u{f136}",
    "mdb": "\u{f8ca}",
    "medapps": "\u{f3c6}",
    "medium": "\u{f23a}",
    "mediumM": "\u{f3c7}",
    "medrt": "\u{f3c8}",
    "meetup": "\u{f2e0}",
    "megaport": "\u{f5a3}",
    "mendeley": "\u{f7b3}",
    "microblog": "\u{e01a}",
    "microsoft": "\u{f3ca}",
    "mix": "\u{f3cb}",
    "mixcloud": "\u{f289}",
    "mixer": "\u{e056}",
    "mizuni": "\u{f3cc}",
    "modx": "\u{f285}",
    "monero": "\u{f3d0}",
    "napster": "\u{f3d2}",
    "neos": "\u{f612}",
    "nimblr": "\u{f5a8}",
    "node": "\u{f419}",
    "nodeJs": "\u{f3d3}",
    "npm": "\u{f3d4}",
    "ns8": "\u{f3d5}",
    "nutritionix": "\u{f3d6}",
    "octopusDeploy": "\u{e082}",
    "odnoklassniki": "\u{f263}",
    "odnoklassnikiSquare": "\u{f264}",
    "oldRepublic": "\u{f510}",
    "opencart": "\u{f23d}",
    "openid": "\u{f19b}",
    "opera": "\u{f26a}",
    "optinMonster": "\u{f23c}",
    "orcid": "\u{f8d2}",
    "osi": "\u{f41a}",
    "page4": "\u{f3d7}",
    "pagelines": "\u{f18c}",
    "palfed": "\u{f3d8}",
    "patreon": "\u{f3d9}",
    "paypal": "\u{f1ed}",
    "pennyArcade": "\u{f704}",
    "perbyte": "\u{e083}",
    "periscope": "\u{f3da}",
    "phabricator": "\u{f3db}",
    "phoenixFramework": "\u{f3dc}",
    "phoenixSquadron": "\u{f511}",
    "php": "\u{f457}",
    "piedPiper": "\u{f2ae}",
    "piedPiperAlt": "\u{f1a8}",
    "piedPiperHat": "\u{f4e5}",
    "piedPiperPp": "\u{f1a7}",
    "piedPiperSquare": "\u{e01e}",
    "pinterest": "\u{f0d2}",
    "pinterestP": "\u{f231}",
    "pinterestSquare": "\u{f0d3}",
    "playstation": "\u{f3df}",
    "productHunt": "\u{f288}",
    "pushed": "\u{f3e1}",
    "python": "\u{f3e2}",
    "qq": "\u{f1d6}",
    "quinscape": "\u{f459}",
    "quora": "\u{f2c4}",
    "rProject": "\u{f4f7}",
    "raspberryPi": "\u{f7bb}",
    "ravelry": "\u{f2d9}",
    "react": "\u{f41b}",
    "reacteurope": "\u{f75d}",
    "readme": "\u{f4d5}",
    "rebel": "\u{f1d0}",
    "redRiver": "\u{f3e3}",
    "reddit": "\u{f1a1}",
    "redditAlien": "\u{f281}",
    "redditSquare": "\u{f1a2}",
    "redhat": "\u{f7bc}",
    "renren": "\u{f18b}",
    "replyd": "\u{f3e6}",
    "researchgate": "\u{f4f8}",
    "resolving": "\u{f3e7}",
    "rev": "\u{f5b2}",
    "rocketchat": "\u{f3e8}",
    "rockrms": "\u{f3e9}",
    "rust": "\u{e07a}",
    "safari": "\u{f267}",
    "salesforce": "\u{f83b}",
    "sass": "\u{f41e}",
    "schlix": "\u{f3ea}",
    "scribd": "\u{f28a}",
    "searchengin": "\u{f3eb}",
    "sellcast": "\u{f2da}",
    "sellsy": "\u{f213}",
    "servicestack": "\u{f3ec}",
    "shirtsinbulk": "\u{f214}",
    "shopify": "\u{e057}",
    "shopware": "\u{f5b5}",
    "simplybuilt": "\u{f215}",
    "sistrix": "\u{f3ee}",
    "sith": "\u{f512}",
    "sketch": "\u{f7c6}",
    "skyatlas": "\u{f216}",
    "skype": "\u{f17e}",
    "slack": "\u{f198}",
    "slackHash": "\u{f3ef}",
    "slideshare": "\u{f1e7}",
    "snapchat": "\u{f2ab}",
    "snapchatGhost": "\u{f2ac}",
    "snapchatSquare": "\u{f2ad}",
    "soundcloud": "\u{f1be}",
    "sourcetree": "\u{f7d3}",
    "speakap": "\u{f3f3}",
    "speakerDeck": "\u{f83c}",
    "spotify": "\u{f1bc}",
    "squarespace": "\u{f5be}",
    "stackExchange": "\u{f18d}",
    "stackOverflow": "\u{f16c}",
    "stackpath": "\u{f842}",
    "staylinked": "\u{f3f5}",
    "steam": "\u{f1b6}",
    "steamSquare": "\u{f1b7}",
    "steamSymbol": "\u{f3f6}",
    "stickerMule": "\u{f3f7}",
    "strava": "\u{f428}",
    "stripe": "\u{f429}",
    "stripeS": "\u{f42a}",
    "studiovinari": "\u{f3f8}",
    "stumbleupon": "\u{f1a4}",
    "stumbleuponCircle": "\u{f1a3}",
    "superpowers": "\u{f2dd}",
    "supple": "\u{f3f9}",
    "suse": "\u{f7d6}",
    "swift": "\u{f8e1}",
    "symfony": "\u{f83d}",
    "teamspeak": "\u{f4f9}",
    "telegram": "\u{f2c6}",
    "telegramPlane": "\u{f3fe}",
    "tencentWeibo": "\u{f1d5}",
    "theRedYeti": "\u{f69d}",
    "themeco": "\u{f5c6}",
    "themeisle": "\u{f2b2}",
    "thinkPeaks": "\u{f731}",
    "tiktok": "\u{e07b}",
    "tradeFederation": "\u{f513}",
    "trello": "\u{f181}",
    "tumblr": "\u{f173}",
    "tumblrSquare": "\u{f174}",
    "twitch": "\u{f1e8}",
    "twitter": "\u{f099}",
    "twitterSquare": "\u{f081}",
    "typo3": "\u{f42b}",
    "uber": "\u{f402}",
    "ubuntu": "\u{f7df}",
    "uikit": "\u{f403}",
    "umbraco": "\u{f8e8}",
    "uncharted": "\u{e084}",
    "uniregistry": "\u{f404}",
    "unity": "\u{e049}",
    "unsplash": "\u{e07c}",
    "untappd": "\u{f405}",
    "ups": "\u{f7e0}",
    "usb": "\u{f287}",
    "usps": "\u{f7e1}",
    "ussunnah": "\u{f407}",
    "vaadin": "\u{f408}",
    "viacoin": "\u{f237}",
    "viadeo": "\u{f2a9}",
    "viadeoSquare": "\u{f2aa}",
    "viber": "\u{f409}",
    "vimeo": "\u{f40a}",
    "vimeoSquare": "\u{f194}",
    "vimeoV": "\u{f27d}",
    "vine": "\u{f1ca}",
    "vk": "\u{f189}",
    "vnv": "\u{f40b}",
    "vuejs": "\u{f41f}",
    "watchmanMonitoring": "\u{e087}",
    "waze": "\u{f83f}",
    "weebly": "\u{f5cc}",
    "weibo": "\u{f18a}",
    "weixin": "\u{f1d7}",
    "whatsapp": "\u{f232}",
    "whatsappSquare": "\u{f40c}",
    "whmcs": "\u{f40d}",
    "wikipediaW": "\u{f266}",
    "windows": "\u{f17a}",
    "wix": "\u{f5cf}",
    "wizardsOfTheCoast": "\u{f730}",
    "wodu": "\u{e088}",
    "wolfPackBattalion": "\u{f514}",
    "wordpress": "\u{f19a}",
    "wordpressSimple": "\u{f411}",
    "wpbeginner": "\u{f297}",
    "wpexplorer": "\u{f2de}",
    "wpforms": "\u{f298}",
    "wpressr": "\u{f3e4}",
    "xbox": "\u{f412}",
    "xing": "\u{f168}",
    "xingSquare": "\u{f169}",
    "yCombinator": "\u{f23b}",
    "yahoo": "\u{f19e}",
    "yammer": "\u{f840}",
    "yandex": "\u{f413}",
    "yandexInternational": "\u{f414}",
    "yarn": "\u{f7e3}",
    "yelp": "\u{f1e9}",
    "yoast": "\u{f2b1}",
    "youtube": "\u{f167}",
    "youtubeSquare": "\u{f431}",
    "zhihu": "\u{f63f}",
]

let faIconsSolid = [
    "ad": "\u{f641}",
    "addressbook": "\u{f2b9}",
    "addresscard": "\u{f2bb}",
    "adjust": "\u{f042}",
    "airfreshener": "\u{f5d0}",
    "aligncenter": "\u{f037}",
    "alignjustify": "\u{f039}",
    "alignleft": "\u{f036}",
    "alignright": "\u{f038}",
    "allergies": "\u{f461}",
    "ambulance": "\u{f0f9}",
    "americansignlanguageinterpreting": "\u{f2a3}",
    "anchor": "\u{f13d}",
    "angledoubledown": "\u{f103}",
    "angledoubleleft": "\u{f100}",
    "angledoubleright": "\u{f101}",
    "angledoubleup": "\u{f102}",
    "angledown": "\u{f107}",
    "angleleft": "\u{f104}",
    "angleright": "\u{f105}",
    "angleup": "\u{f106}",
    "angry": "\u{f556}",
    "ankh": "\u{f644}",
    "applealt": "\u{f5d1}",
    "archive": "\u{f187}",
    "archway": "\u{f557}",
    "arrowaltcircledown": "\u{f358}",
    "arrowaltcircleleft": "\u{f359}",
    "arrowaltcircleright": "\u{f35a}",
    "arrowaltcircleup": "\u{f35b}",
    "arrowcircledown": "\u{f0ab}",
    "arrowcircleleft": "\u{f0a8}",
    "arrowcircleright": "\u{f0a9}",
    "arrowcircleup": "\u{f0aa}",
    "arrowdown": "\u{f063}",
    "arrowleft": "\u{f060}",
    "arrowright": "\u{f061}",
    "arrowup": "\u{f062}",
    "arrowsalt": "\u{f0b2}",
    "arrowsalth": "\u{f337}",
    "arrowsaltv": "\u{f338}",
    "assistivelisteningsystems": "\u{f2a2}",
    "asterisk": "\u{f069}",
    "at": "\u{f1fa}",
    "atlas": "\u{f558}",
    "atom": "\u{f5d2}",
    "audiodescription": "\u{f29e}",
    "award": "\u{f559}",
    "baby": "\u{f77c}",
    "babycarriage": "\u{f77d}",
    "backspace": "\u{f55a}",
    "backward": "\u{f04a}",
    "bacon": "\u{f7e5}",
    "bacteria": "\u{e059}",
    "bacterium": "\u{e05a}",
    "bahai": "\u{f666}",
    "balancescale": "\u{f24e}",
    "balancescaleleft": "\u{f515}",
    "balancescaleright": "\u{f516}",
    "ban": "\u{f05e}",
    "bandaid": "\u{f462}",
    "barcode": "\u{f02a}",
    "bars": "\u{f0c9}",
    "baseballball": "\u{f433}",
    "basketballball": "\u{f434}",
    "bath": "\u{f2cd}",
    "batteryempty": "\u{f244}",
    "batteryfull": "\u{f240}",
    "batteryhalf": "\u{f242}",
    "batteryquarter": "\u{f243}",
    "batterythreequarters": "\u{f241}",
    "bed": "\u{f236}",
    "beer": "\u{f0fc}",
    "bell": "\u{f0f3}",
    "bellslash": "\u{f1f6}",
    "beziercurve": "\u{f55b}",
    "bible": "\u{f647}",
    "bicycle": "\u{f206}",
    "biking": "\u{f84a}",
    "binoculars": "\u{f1e5}",
    "biohazard": "\u{f780}",
    "birthdaycake": "\u{f1fd}",
    "blender": "\u{f517}",
    "blenderphone": "\u{f6b6}",
    "blind": "\u{f29d}",
    "blog": "\u{f781}",
    "bold": "\u{f032}",
    "bolt": "\u{f0e7}",
    "bomb": "\u{f1e2}",
    "bone": "\u{f5d7}",
    "bong": "\u{f55c}",
    "book": "\u{f02d}",
    "bookdead": "\u{f6b7}",
    "bookmedical": "\u{f7e6}",
    "bookopen": "\u{f518}",
    "bookreader": "\u{f5da}",
    "bookmark": "\u{f02e}",
    "borderall": "\u{f84c}",
    "bordernone": "\u{f850}",
    "borderstyle": "\u{f853}",
    "bowlingball": "\u{f436}",
    "box": "\u{f466}",
    "boxopen": "\u{f49e}",
    "boxtissue": "\u{e05b}",
    "boxes": "\u{f468}",
    "braille": "\u{f2a1}",
    "brain": "\u{f5dc}",
    "breadslice": "\u{f7ec}",
    "brief": "\u{f0b1}",
    "briefcasemedical": "\u{f469}",
    "broadcasttower": "\u{f519}",
    "broom": "\u{f51a}",
    "brush": "\u{f55d}",
    "bug": "\u{f188}",
    "building": "\u{f1ad}",
    "bullhorn": "\u{f0a1}",
    "bullseye": "\u{f140}",
    "burn": "\u{f46a}",
    "bus": "\u{f207}",
    "busalt": "\u{f55e}",
    "businesstime": "\u{f64a}",
    "calculator": "\u{f1ec}",
    "calendar": "\u{f133}",
    "calendaralt": "\u{f073}",
    "calendarcheck": "\u{f274}",
    "calendarday": "\u{f783}",
    "calendarminus": "\u{f272}",
    "calendarplus": "\u{f271}",
    "calendartimes": "\u{f273}",
    "calendarweek": "\u{f784}",
    "camera": "\u{f030}",
    "cameraretro": "\u{f083}",
    "campground": "\u{f6bb}",
    "candycane": "\u{f786}",
    "cannabis": "\u{f55f}",
    "capsules": "\u{f46b}",
    "car": "\u{f1b9}",
    "caralt": "\u{f5de}",
    "carbattery": "\u{f5df}",
    "carcrash": "\u{f5e1}",
    "carside": "\u{f5e4}",
    "caravan": "\u{f8ff}",
    "caretdown": "\u{f0d7}",
    "caretleft": "\u{f0d9}",
    "caretright": "\u{f0da}",
    "caretsquaredown": "\u{f150}",
    "caretsquareleft": "\u{f191}",
    "caretsquareright": "\u{f152}",
    "caretsquareup": "\u{f151}",
    "caretup": "\u{f0d8}",
    "carrot": "\u{f787}",
    "cartarrowdown": "\u{f218}",
    "cartplus": "\u{f217}",
    "cashregister": "\u{f788}",
    "cat": "\u{f6be}",
    "certificate": "\u{f0a3}",
    "chair": "\u{f6c0}",
    "chalkboard": "\u{f51b}",
    "chalkboardteacher": "\u{f51c}",
    "chargingstation": "\u{f5e7}",
    "chartarea": "\u{f1fe}",
    "chartbar": "\u{f080}",
    "chartline": "\u{f201}",
    "chartpie": "\u{f200}",
    "check": "\u{f00c}",
    "checkcircle": "\u{f058}",
    "checkdouble": "\u{f560}",
    "checksquare": "\u{f14a}",
    "cheese": "\u{f7ef}",
    "chess": "\u{f439}",
    "chessbishop": "\u{f43a}",
    "chessboard": "\u{f43c}",
    "chessking": "\u{f43f}",
    "chessknight": "\u{f441}",
    "chesspawn": "\u{f443}",
    "chessqueen": "\u{f445}",
    "chessrook": "\u{f447}",
    "chevroncircledown": "\u{f13a}",
    "chevroncircleleft": "\u{f137}",
    "chevroncircleright": "\u{f138}",
    "chevroncircleup": "\u{f139}",
    "chevrondown": "\u{f078}",
    "chevronleft": "\u{f053}",
    "chevronright": "\u{f054}",
    "chevronup": "\u{f077}",
    "child": "\u{f1ae}",
    "church": "\u{f51d}",
    "circle": "\u{f111}",
    "circlenotch": "\u{f1ce}",
    "city": "\u{f64f}",
    "clinicmedical": "\u{f7f2}",
    "clipboard": "\u{f328}",
    "clipboardcheck": "\u{f46c}",
    "clipboardlist": "\u{f46d}",
    "clock": "\u{f017}",
    "clone": "\u{f24d}",
    "closedcaptioning": "\u{f20a}",
    "cloud": "\u{f0c2}",
    "clouddownloadalt": "\u{f381}",
    "cloudmeatball": "\u{f73b}",
    "cloudmoon": "\u{f6c3}",
    "cloudmoonrain": "\u{f73c}",
    "cloudrain": "\u{f73d}",
    "cloudshowersheavy": "\u{f740}",
    "cloudsun": "\u{f6c4}",
    "cloudsunrain": "\u{f743}",
    "clouduploadalt": "\u{f382}",
    "cocktail": "\u{f561}",
    "code": "\u{f121}",
    "codebranch": "\u{f126}",
    "coffee": "\u{f0f4}",
    "cog": "\u{f013}",
    "cogs": "\u{f085}",
    "coins": "\u{f51e}",
    "columns": "\u{f0db}",
    "comment": "\u{f075}",
    "commentalt": "\u{f27a}",
    "commentdollar": "\u{f651}",
    "commentdots": "\u{f4ad}",
    "commentmedical": "\u{f7f5}",
    "commentslash": "\u{f4b3}",
    "comments": "\u{f086}",
    "commentsdollar": "\u{f653}",
    "compactdisc": "\u{f51f}",
    "compass": "\u{f14e}",
    "compress": "\u{f066}",
    "compressalt": "\u{f422}",
    "compressarrowsalt": "\u{f78c}",
    "conciergebell": "\u{f562}",
    "cookie": "\u{f563}",
    "cookiebite": "\u{f564}",
    "copy": "\u{f0c5}",
    "copyright": "\u{f1f9}",
    "couch": "\u{f4b8}",
    "creditcard": "\u{f09d}",
    "crop": "\u{f125}",
    "cropalt": "\u{f565}",
    "cross": "\u{f654}",
    "crosshairs": "\u{f05b}",
    "crow": "\u{f520}",
    "crown": "\u{f521}",
    "crutch": "\u{f7f7}",
    "cube": "\u{f1b2}",
    "cubes": "\u{f1b3}",
    "cut": "\u{f0c4}",
    "database": "\u{f1c0}",
    "deaf": "\u{f2a4}",
    "democrat": "\u{f747}",
    "desktop": "\u{f108}",
    "dharmachakra": "\u{f655}",
    "diagnoses": "\u{f470}",
    "dice": "\u{f522}",
    "diced20": "\u{f6cf}",
    "diced6": "\u{f6d1}",
    "dicefive": "\u{f523}",
    "dicefour": "\u{f524}",
    "diceone": "\u{f525}",
    "dicesix": "\u{f526}",
    "dicethree": "\u{f527}",
    "dicetwo": "\u{f528}",
    "digitaltachograph": "\u{f566}",
    "directions": "\u{f5eb}",
    "disease": "\u{f7fa}",
    "divide": "\u{f529}",
    "dizzy": "\u{f567}",
    "dna": "\u{f471}",
    "dog": "\u{f6d3}",
    "dollarsign": "\u{f155}",
    "dolly": "\u{f472}",
    "dollyflatbed": "\u{f474}",
    "donate": "\u{f4b9}",
    "doorclosed": "\u{f52a}",
    "dooropen": "\u{f52b}",
    "dotcircle": "\u{f192}",
    "dove": "\u{f4ba}",
    "download": "\u{f019}",
    "draftingcompass": "\u{f568}",
    "dragon": "\u{f6d5}",
    "drawpolygon": "\u{f5ee}",
    "drum": "\u{f569}",
    "drumsteelpan": "\u{f56a}",
    "drumstickbite": "\u{f6d7}",
    "dumbbell": "\u{f44b}",
    "dumpster": "\u{f793}",
    "dumpsterfire": "\u{f794}",
    "dungeon": "\u{f6d9}",
    "edit": "\u{f044}",
    "egg": "\u{f7fb}",
    "eject": "\u{f052}",
    "ellipsish": "\u{f141}",
    "ellipsisv": "\u{f142}",
    "envelope": "\u{f0e0}",
    "envelopeopen": "\u{f2b6}",
    "envelopeopentext": "\u{f658}",
    "envelopesquare": "\u{f199}",
    "equals": "\u{f52c}",
    "eraser": "\u{f12d}",
    "ethernet": "\u{f796}",
    "eurosign": "\u{f153}",
    "exchangealt": "\u{f362}",
    "exclamation": "\u{f12a}",
    "exclamationcircle": "\u{f06a}",
    "exclamationtriangle": "\u{f071}",
    "expand": "\u{f065}",
    "expandalt": "\u{f424}",
    "expandarrowsalt": "\u{f31e}",
    "externallinkalt": "\u{f35d}",
    "externallinksquarealt": "\u{f360}",
    "eye": "\u{f06e}",
    "eyedropper": "\u{f1fb}",
    "eyeslash": "\u{f070}",
    "fan": "\u{f863}",
    "fastbackward": "\u{f049}",
    "fastforward": "\u{f050}",
    "faucet": "\u{e005}",
    "fax": "\u{f1ac}",
    "feather": "\u{f52d}",
    "featheralt": "\u{f56b}",
    "female": "\u{f182}",
    "fighterjet": "\u{f0fb}",
    "file": "\u{f15b}",
    "filealt": "\u{f15c}",
    "filearchive": "\u{f1c6}",
    "fileaudio": "\u{f1c7}",
    "filecode": "\u{f1c9}",
    "filecontract": "\u{f56c}",
    "filecsv": "\u{f6dd}",
    "filedownload": "\u{f56d}",
    "fileexcel": "\u{f1c3}",
    "fileexport": "\u{f56e}",
    "fileimage": "\u{f1c5}",
    "fileimport": "\u{f56f}",
    "fileinvoice": "\u{f570}",
    "fileinvoicedollar": "\u{f571}",
    "filemedical": "\u{f477}",
    "filemedicalalt": "\u{f478}",
    "filepdf": "\u{f1c1}",
    "filepowerpoint": "\u{f1c4}",
    "fileprescription": "\u{f572}",
    "filesignature": "\u{f573}",
    "fileupload": "\u{f574}",
    "filevideo": "\u{f1c8}",
    "fileword": "\u{f1c2}",
    "fill": "\u{f575}",
    "filldrip": "\u{f576}",
    "film": "\u{f008}",
    "filter": "\u{f0b0}",
    "fingerprint": "\u{f577}",
    "fire": "\u{f06d}",
    "firealt": "\u{f7e4}",
    "fireextinguisher": "\u{f134}",
    "firstaid": "\u{f479}",
    "fish": "\u{f578}",
    "fistraised": "\u{f6de}",
    "flag": "\u{f024}",
    "flagcheckered": "\u{f11e}",
    "flagusa": "\u{f74d}",
    "flask": "\u{f0c3}",
    "flushed": "\u{f579}",
    "folder": "\u{f07b}",
    "folderminus": "\u{f65d}",
    "folderopen": "\u{f07c}",
    "folderplus": "\u{f65e}",
    "font": "\u{f031}",
    "footballball": "\u{f44e}",
    "forward": "\u{f04e}",
    "frog": "\u{f52e}",
    "frown": "\u{f119}",
    "frownopen": "\u{f57a}",
    "funneldollar": "\u{f662}",
    "futbol": "\u{f1e3}",
    "gamepad": "\u{f11b}",
    "gaspump": "\u{f52f}",
    "gavel": "\u{f0e3}",
    "gem": "\u{f3a5}",
    "genderless": "\u{f22d}",
    "ghost": "\u{f6e2}",
    "gift": "\u{f06b}",
    "gifts": "\u{f79c}",
    "glasscheers": "\u{f79f}",
    "glassmartini": "\u{f000}",
    "glassmartinialt": "\u{f57b}",
    "glasswhiskey": "\u{f7a0}",
    "glasses": "\u{f530}",
    "globe": "\u{f0ac}",
    "globeafrica": "\u{f57c}",
    "globeamericas": "\u{f57d}",
    "globeasia": "\u{f57e}",
    "globeeurope": "\u{f7a2}",
    "golfball": "\u{f450}",
    "gopuram": "\u{f664}",
    "graduationcap": "\u{f19d}",
    "greaterthan": "\u{f531}",
    "greaterthanequal": "\u{f532}",
    "grimace": "\u{f57f}",
    "grin": "\u{f580}",
    "grinalt": "\u{f581}",
    "grinbeam": "\u{f582}",
    "grinbeamsweat": "\u{f583}",
    "grinhearts": "\u{f584}",
    "grinsquint": "\u{f585}",
    "grinsquinttears": "\u{f586}",
    "grinstars": "\u{f587}",
    "grintears": "\u{f588}",
    "grintongue": "\u{f589}",
    "grintonguesquint": "\u{f58a}",
    "grintonguewink": "\u{f58b}",
    "grinwink": "\u{f58c}",
    "griphorizontal": "\u{f58d}",
    "griplines": "\u{f7a4}",
    "griplinesvertical": "\u{f7a5}",
    "gripvertical": "\u{f58e}",
    "guitar": "\u{f7a6}",
    "hsquare": "\u{f0fd}",
    "hamburger": "\u{f805}",
    "hammer": "\u{f6e3}",
    "hamsa": "\u{f665}",
    "handholding": "\u{f4bd}",
    "handholdingheart": "\u{f4be}",
    "handholdingmedical": "\u{e05c}",
    "handholdingusd": "\u{f4c0}",
    "handholdingwater": "\u{f4c1}",
    "handlizard": "\u{f258}",
    "handmiddlefinger": "\u{f806}",
    "handpaper": "\u{f256}",
    "handpeace": "\u{f25b}",
    "handpointdown": "\u{f0a7}",
    "handpointleft": "\u{f0a5}",
    "handpointright": "\u{f0a4}",
    "handpointup": "\u{f0a6}",
    "handpointer": "\u{f25a}",
    "handrock": "\u{f255}",
    "handscissors": "\u{f257}",
    "handsparkles": "\u{e05d}",
    "handspock": "\u{f259}",
    "hands": "\u{f4c2}",
    "handshelping": "\u{f4c4}",
    "handswash": "\u{e05e}",
    "handshake": "\u{f2b5}",
    "handshakealtslash": "\u{e05f}",
    "handshakeslash": "\u{e060}",
    "hanukiah": "\u{f6e6}",
    "hardhat": "\u{f807}",
    "hashtag": "\u{f292}",
    "hatcowboy": "\u{f8c0}",
    "hatcowboyside": "\u{f8c1}",
    "hatwizard": "\u{f6e8}",
    "hdd": "\u{f0a0}",
    "headsidecough": "\u{e061}",
    "headsidecoughslash": "\u{e062}",
    "headsidemask": "\u{e063}",
    "headsidevirus": "\u{e064}",
    "heading": "\u{f1dc}",
    "headphones": "\u{f025}",
    "headphonesalt": "\u{f58f}",
    "headset": "\u{f590}",
    "heart": "\u{f004}",
    "heartbroken": "\u{f7a9}",
    "heartbeat": "\u{f21e}",
    "helicopter": "\u{f533}",
    "highlighter": "\u{f591}",
    "hiking": "\u{f6ec}",
    "hippo": "\u{f6ed}",
    "history": "\u{f1da}",
    "hockeypuck": "\u{f453}",
    "hollyberry": "\u{f7aa}",
    "home": "\u{f015}",
    "horse": "\u{f6f0}",
    "horsehead": "\u{f7ab}",
    "hospital": "\u{f0f8}",
    "hospitalalt": "\u{f47d}",
    "hospitalsymbol": "\u{f47e}",
    "hospitaluser": "\u{f80d}",
    "hottub": "\u{f593}",
    "hotdog": "\u{f80f}",
    "hotel": "\u{f594}",
    "hourglass": "\u{f254}",
    "hourglassend": "\u{f253}",
    "hourglasshalf": "\u{f252}",
    "hourglassstart": "\u{f251}",
    "housedamage": "\u{f6f1}",
    "houseuser": "\u{e065}",
    "hryvnia": "\u{f6f2}",
    "icursor": "\u{f246}",
    "icecream": "\u{f810}",
    "icicles": "\u{f7ad}",
    "icons": "\u{f86d}",
    "idbadge": "\u{f2c1}",
    "idcard": "\u{f2c2}",
    "idcardalt": "\u{f47f}",
    "igloo": "\u{f7ae}",
    "image": "\u{f03e}",
    "images": "\u{f302}",
    "inbox": "\u{f01c}",
    "indent": "\u{f03c}",
    "industry": "\u{f275}",
    "infinity": "\u{f534}",
    "info": "\u{f129}",
    "infocircle": "\u{f05a}",
    "italic": "\u{f033}",
    "jedi": "\u{f669}",
    "joint": "\u{f595}",
    "journalwhills": "\u{f66a}",
    "kaaba": "\u{f66b}",
    "key": "\u{f084}",
    "keyboard": "\u{f11c}",
    "khanda": "\u{f66d}",
    "kiss": "\u{f596}",
    "kissbeam": "\u{f597}",
    "kisswinkheart": "\u{f598}",
    "kiwibird": "\u{f535}",
    "landmark": "\u{f66f}",
    "language": "\u{f1ab}",
    "laptop": "\u{f109}",
    "laptopcode": "\u{f5fc}",
    "laptophouse": "\u{e066}",
    "laptopmedical": "\u{f812}",
    "laugh": "\u{f599}",
    "laughbeam": "\u{f59a}",
    "laughsquint": "\u{f59b}",
    "laughwink": "\u{f59c}",
    "layergroup": "\u{f5fd}",
    "leaf": "\u{f06c}",
    "lemon": "\u{f094}",
    "lessthan": "\u{f536}",
    "lessthanequal": "\u{f537}",
    "leveldownalt": "\u{f3be}",
    "levelupalt": "\u{f3bf}",
    "lifering": "\u{f1cd}",
    "lightbulb": "\u{f0eb}",
    "link": "\u{f0c1}",
    "lirasign": "\u{f195}",
    "list": "\u{f03a}",
    "listalt": "\u{f022}",
    "listol": "\u{f0cb}",
    "listul": "\u{f0ca}",
    "locationarrow": "\u{f124}",
    "lock": "\u{f023}",
    "lockopen": "\u{f3c1}",
    "longarrowaltdown": "\u{f309}",
    "longarrowaltleft": "\u{f30a}",
    "longarrowaltright": "\u{f30b}",
    "longarrowaltup": "\u{f30c}",
    "lowvision": "\u{f2a8}",
    "luggagecart": "\u{f59d}",
    "lungs": "\u{f604}",
    "lungsvirus": "\u{e067}",
    "magic": "\u{f0d0}",
    "magnet": "\u{f076}",
    "mailbulk": "\u{f674}",
    "male": "\u{f183}",
    "map": "\u{f279}",
    "mapmarked": "\u{f59f}",
    "mapmarkedalt": "\u{f5a0}",
    "mapmarker": "\u{f041}",
    "mapmarkeralt": "\u{f3c5}",
    "mappin": "\u{f276}",
    "mapsigns": "\u{f277}",
    "marker": "\u{f5a1}",
    "mars": "\u{f222}",
    "marsdouble": "\u{f227}",
    "marsstroke": "\u{f229}",
    "marsstrokeh": "\u{f22b}",
    "marsstrokev": "\u{f22a}",
    "mask": "\u{f6fa}",
    "medal": "\u{f5a2}",
    "medkit": "\u{f0fa}",
    "meh": "\u{f11a}",
    "mehblank": "\u{f5a4}",
    "mehrollingeyes": "\u{f5a5}",
    "memory": "\u{f538}",
    "menorah": "\u{f676}",
    "mercury": "\u{f223}",
    "meteor": "\u{f753}",
    "microchip": "\u{f2db}",
    "microphone": "\u{f130}",
    "microphonealt": "\u{f3c9}",
    "microphonealtslash": "\u{f539}",
    "microphoneslash": "\u{f131}",
    "microscope": "\u{f610}",
    "minus": "\u{f068}",
    "minuscircle": "\u{f056}",
    "minussquare": "\u{f146}",
    "mitten": "\u{f7b5}",
    "mobile": "\u{f10b}",
    "mobilealt": "\u{f3cd}",
    "moneybill": "\u{f0d6}",
    "moneybillalt": "\u{f3d1}",
    "moneybillwave": "\u{f53a}",
    "moneybillwavealt": "\u{f53b}",
    "moneycheck": "\u{f53c}",
    "moneycheckalt": "\u{f53d}",
    "monument": "\u{f5a6}",
    "moon": "\u{f186}",
    "mortarpestle": "\u{f5a7}",
    "mosque": "\u{f678}",
    "motorcycle": "\u{f21c}",
    "mountain": "\u{f6fc}",
    "mouse": "\u{f8cc}",
    "mousepointer": "\u{f245}",
    "mughot": "\u{f7b6}",
    "music": "\u{f001}",
    "networkwired": "\u{f6ff}",
    "neuter": "\u{f22c}",
    "newspaper": "\u{f1ea}",
    "notequal": "\u{f53e}",
    "notesmedical": "\u{f481}",
    "objectgroup": "\u{f247}",
    "objectungroup": "\u{f248}",
    "oilcan": "\u{f613}",
    "om": "\u{f679}",
    "otter": "\u{f700}",
    "outdent": "\u{f03b}",
    "pager": "\u{f815}",
    "paintbrush": "\u{f1fc}",
    "paintroller": "\u{f5aa}",
    "palette": "\u{f53f}",
    "pallet": "\u{f482}",
    "paperplane": "\u{f1d8}",
    "paperclip": "\u{f0c6}",
    "parachutebox": "\u{f4cd}",
    "paragraph": "\u{f1dd}",
    "parking": "\u{f540}",
    "passport": "\u{f5ab}",
    "pastafarianism": "\u{f67b}",
    "paste": "\u{f0ea}",
    "pause": "\u{f04c}",
    "pausecircle": "\u{f28b}",
    "paw": "\u{f1b0}",
    "peace": "\u{f67c}",
    "pen": "\u{f304}",
    "penalt": "\u{f305}",
    "penfancy": "\u{f5ac}",
    "pennib": "\u{f5ad}",
    "pensquare": "\u{f14b}",
    "pencilalt": "\u{f303}",
    "pencilruler": "\u{f5ae}",
    "peoplearrows": "\u{e068}",
    "peoplecarry": "\u{f4ce}",
    "pepperhot": "\u{f816}",
    "percent": "\u{f295}",
    "percentage": "\u{f541}",
    "personbooth": "\u{f756}",
    "phone": "\u{f095}",
    "phonealt": "\u{f879}",
    "phoneslash": "\u{f3dd}",
    "phonesquare": "\u{f098}",
    "phonesquarealt": "\u{f87b}",
    "phonevolume": "\u{f2a0}",
    "photovideo": "\u{f87c}",
    "piggybank": "\u{f4d3}",
    "pills": "\u{f484}",
    "pizzaslice": "\u{f818}",
    "placeofworship": "\u{f67f}",
    "plane": "\u{f072}",
    "planearrival": "\u{f5af}",
    "planedeparture": "\u{f5b0}",
    "planeslash": "\u{e069}",
    "play": "\u{f04b}",
    "playcircle": "\u{f144}",
    "plug": "\u{f1e6}",
    "plus": "\u{f067}",
    "pluscircle": "\u{f055}",
    "plussquare": "\u{f0fe}",
    "podcast": "\u{f2ce}",
    "poll": "\u{f681}",
    "pollh": "\u{f682}",
    "poo": "\u{f2fe}",
    "poostorm": "\u{f75a}",
    "poop": "\u{f619}",
    "portrait": "\u{f3e0}",
    "poundsign": "\u{f154}",
    "poweroff": "\u{f011}",
    "pray": "\u{f683}",
    "prayinghands": "\u{f684}",
    "prescription": "\u{f5b1}",
    "prescriptionbottle": "\u{f485}",
    "prescriptionbottlealt": "\u{f486}",
    "print": "\u{f02f}",
    "procedures": "\u{f487}",
    "projectdiagram": "\u{f542}",
    "pumpmedical": "\u{e06a}",
    "pumpsoap": "\u{e06b}",
    "puzzlepiece": "\u{f12e}",
    "qrcode": "\u{f029}",
    "question": "\u{f128}",
    "questioncircle": "\u{f059}",
    "quidditch": "\u{f458}",
    "quoteleft": "\u{f10d}",
    "quoteright": "\u{f10e}",
    "quran": "\u{f687}",
    "radiation": "\u{f7b9}",
    "radiationalt": "\u{f7ba}",
    "rainbow": "\u{f75b}",
    "random": "\u{f074}",
    "receipt": "\u{f543}",
    "recordvinyl": "\u{f8d9}",
    "recycle": "\u{f1b8}",
    "redo": "\u{f01e}",
    "redoalt": "\u{f2f9}",
    "registered": "\u{f25d}",
    "removeformat": "\u{f87d}",
    "reply": "\u{f3e5}",
    "replyall": "\u{f122}",
    "republican": "\u{f75e}",
    "restroom": "\u{f7bd}",
    "retweet": "\u{f079}",
    "ribbon": "\u{f4d6}",
    "ring": "\u{f70b}",
    "road": "\u{f018}",
    "robot": "\u{f544}",
    "rocket": "\u{f135}",
    "route": "\u{f4d7}",
    "rss": "\u{f09e}",
    "rsssquare": "\u{f143}",
    "rublesign": "\u{f158}",
    "ruler": "\u{f545}",
    "rulercombined": "\u{f546}",
    "rulerhorizontal": "\u{f547}",
    "rulervertical": "\u{f548}",
    "running": "\u{f70c}",
    "rupeesign": "\u{f156}",
    "sadcry": "\u{f5b3}",
    "sadtear": "\u{f5b4}",
    "satellite": "\u{f7bf}",
    "satellitedish": "\u{f7c0}",
    "save": "\u{f0c7}",
    "school": "\u{f549}",
    "screwdriver": "\u{f54a}",
    "scroll": "\u{f70e}",
    "sdcard": "\u{f7c2}",
    "search": "\u{f002}",
    "searchdollar": "\u{f688}",
    "searchlocation": "\u{f689}",
    "searchminus": "\u{f010}",
    "searchplus": "\u{f00e}",
    "seedling": "\u{f4d8}",
    "server": "\u{f233}",
    "shapes": "\u{f61f}",
    "share": "\u{f064}",
    "sharealt": "\u{f1e0}",
    "sharealtsquare": "\u{f1e1}",
    "sharesquare": "\u{f14d}",
    "shekelsign": "\u{f20b}",
    "shieldalt": "\u{f3ed}",
    "shieldvirus": "\u{e06c}",
    "ship": "\u{f21a}",
    "shippingfast": "\u{f48b}",
    "shoeprints": "\u{f54b}",
    "shoppingbag": "\u{f290}",
    "shoppingbasket": "\u{f291}",
    "shoppingcart": "\u{f07a}",
    "shower": "\u{f2cc}",
    "shuttlevan": "\u{f5b6}",
    "sign": "\u{f4d9}",
    "signinalt": "\u{f2f6}",
    "signlanguage": "\u{f2a7}",
    "signoutalt": "\u{f2f5}",
    "signal": "\u{f012}",
    "signature": "\u{f5b7}",
    "simcard": "\u{f7c4}",
    "sink": "\u{e06d}",
    "sitemap": "\u{f0e8}",
    "skating": "\u{f7c5}",
    "skiing": "\u{f7c9}",
    "skiingnordic": "\u{f7ca}",
    "skull": "\u{f54c}",
    "skullcrossbones": "\u{f714}",
    "slash": "\u{f715}",
    "sleigh": "\u{f7cc}",
    "slidersh": "\u{f1de}",
    "smile": "\u{f118}",
    "smilebeam": "\u{f5b8}",
    "smilewink": "\u{f4da}",
    "smog": "\u{f75f}",
    "smoking": "\u{f48d}",
    "smokingban": "\u{f54d}",
    "sms": "\u{f7cd}",
    "snowboarding": "\u{f7ce}",
    "snowflake": "\u{f2dc}",
    "snowman": "\u{f7d0}",
    "snowplow": "\u{f7d2}",
    "soap": "\u{e06e}",
    "socks": "\u{f696}",
    "solarpanel": "\u{f5ba}",
    "sort": "\u{f0dc}",
    "sortalphadown": "\u{f15d}",
    "sortalphadownalt": "\u{f881}",
    "sortalphaup": "\u{f15e}",
    "sortalphaupalt": "\u{f882}",
    "sortamountdown": "\u{f160}",
    "sortamountdownalt": "\u{f884}",
    "sortamountup": "\u{f161}",
    "sortamountupalt": "\u{f885}",
    "sortdown": "\u{f0dd}",
    "sortnumericdown": "\u{f162}",
    "sortnumericdownalt": "\u{f886}",
    "sortnumericup": "\u{f163}",
    "sortnumericupalt": "\u{f887}",
    "sortup": "\u{f0de}",
    "spa": "\u{f5bb}",
    "spaceshuttle": "\u{f197}",
    "spellcheck": "\u{f891}",
    "spider": "\u{f717}",
    "spinner": "\u{f110}",
    "splotch": "\u{f5bc}",
    "spraycan": "\u{f5bd}",
    "square": "\u{f0c8}",
    "squarefull": "\u{f45c}",
    "squarerootalt": "\u{f698}",
    "stamp": "\u{f5bf}",
    "star": "\u{f005}",
    "starandcrescent": "\u{f699}",
    "starhalf": "\u{f089}",
    "starhalfalt": "\u{f5c0}",
    "starofdavid": "\u{f69a}",
    "staroflife": "\u{f621}",
    "stepbackward": "\u{f048}",
    "stepforward": "\u{f051}",
    "stethoscope": "\u{f0f1}",
    "stickynote": "\u{f249}",
    "stop": "\u{f04d}",
    "stopcircle": "\u{f28d}",
    "stopwatch": "\u{f2f2}",
    "stopwatch20": "\u{e06f}",
    "store": "\u{f54e}",
    "storealt": "\u{f54f}",
    "storealtslash": "\u{e070}",
    "storeslash": "\u{e071}",
    "stream": "\u{f550}",
    "streetview": "\u{f21d}",
    "strikethrough": "\u{f0cc}",
    "stroopwafel": "\u{f551}",
    "`subscript`": "\u{f12c}",
    "subway": "\u{f239}",
    "suit": "\u{f0f2}",
    "suitcaserolling": "\u{f5c1}",
    "sun": "\u{f185}",
    "superscript": "\u{f12b}",
    "surprise": "\u{f5c2}",
    "swatchbook": "\u{f5c3}",
    "swimmer": "\u{f5c4}",
    "swimmingpool": "\u{f5c5}",
    "synagogue": "\u{f69b}",
    "sync": "\u{f021}",
    "syncalt": "\u{f2f1}",
    "syringe": "\u{f48e}",
    "table": "\u{f0ce}",
    "tabletennis": "\u{f45d}",
    "tablet": "\u{f10a}",
    "tabletalt": "\u{f3fa}",
    "tablets": "\u{f490}",
    "tachometeralt": "\u{f3fd}",
    "tag": "\u{f02b}",
    "tags": "\u{f02c}",
    "tape": "\u{f4db}",
    "tasks": "\u{f0ae}",
    "taxi": "\u{f1ba}",
    "teeth": "\u{f62e}",
    "teethopen": "\u{f62f}",
    "temperaturehigh": "\u{f769}",
    "temperaturelow": "\u{f76b}",
    "tenge": "\u{f7d7}",
    "terminal": "\u{f120}",
    "textheight": "\u{f034}",
    "textwidth": "\u{f035}",
    "th": "\u{f00a}",
    "thlarge": "\u{f009}",
    "thlist": "\u{f00b}",
    "theatermasks": "\u{f630}",
    "thermometer": "\u{f491}",
    "thermometerempty": "\u{f2cb}",
    "thermometerfull": "\u{f2c7}",
    "thermometerhalf": "\u{f2c9}",
    "thermometerquarter": "\u{f2ca}",
    "thermometerthreequarters": "\u{f2c8}",
    "thumbsdown": "\u{f165}",
    "thumbsup": "\u{f164}",
    "thumbtack": "\u{f08d}",
    "ticketalt": "\u{f3ff}",
    "times": "\u{f00d}",
    "timescircle": "\u{f057}",
    "tint": "\u{f043}",
    "tintslash": "\u{f5c7}",
    "tired": "\u{f5c8}",
    "toggleoff": "\u{f204}",
    "toggleon": "\u{f205}",
    "toilet": "\u{f7d8}",
    "toiletpaper": "\u{f71e}",
    "toiletpaperslash": "\u{e072}",
    "toolbox": "\u{f552}",
    "tools": "\u{f7d9}",
    "tooth": "\u{f5c9}",
    "torah": "\u{f6a0}",
    "toriigate": "\u{f6a1}",
    "tractor": "\u{f722}",
    "trademark": "\u{f25c}",
    "trafficlight": "\u{f637}",
    "trailer": "\u{e041}",
    "train": "\u{f238}",
    "tram": "\u{f7da}",
    "transgender": "\u{f224}",
    "transgenderalt": "\u{f225}",
    "trash": "\u{f1f8}",
    "trashalt": "\u{f2ed}",
    "trashrestore": "\u{f829}",
    "trashrestorealt": "\u{f82a}",
    "tree": "\u{f1bb}",
    "trophy": "\u{f091}",
    "truck": "\u{f0d1}",
    "truckloading": "\u{f4de}",
    "truckmonster": "\u{f63b}",
    "truckmoving": "\u{f4df}",
    "truckpickup": "\u{f63c}",
    "tshirt": "\u{f553}",
    "tty": "\u{f1e4}",
    "tv": "\u{f26c}",
    "umbrella": "\u{f0e9}",
    "umbrellabeach": "\u{f5ca}",
    "underline": "\u{f0cd}",
    "undo": "\u{f0e2}",
    "undoalt": "\u{f2ea}",
    "universalaccess": "\u{f29a}",
    "university": "\u{f19c}",
    "unlink": "\u{f127}",
    "unlock": "\u{f09c}",
    "unlockalt": "\u{f13e}",
    "upload": "\u{f093}",
    "user": "\u{f007}",
    "useralt": "\u{f406}",
    "useraltslash": "\u{f4fa}",
    "userastronaut": "\u{f4fb}",
    "usercheck": "\u{f4fc}",
    "usercircle": "\u{f2bd}",
    "userclock": "\u{f4fd}",
    "usercog": "\u{f4fe}",
    "useredit": "\u{f4ff}",
    "userfriends": "\u{f500}",
    "usergraduate": "\u{f501}",
    "userinjured": "\u{f728}",
    "userlock": "\u{f502}",
    "usermd": "\u{f0f0}",
    "userminus": "\u{f503}",
    "userninja": "\u{f504}",
    "usernurse": "\u{f82f}",
    "userplus": "\u{f234}",
    "usersecret": "\u{f21b}",
    "usershield": "\u{f505}",
    "userslash": "\u{f506}",
    "usertag": "\u{f507}",
    "usertie": "\u{f508}",
    "usertimes": "\u{f235}",
    "users": "\u{f0c0}",
    "userscog": "\u{f509}",
    "usersslash": "\u{e073}",
    "utensilspoon": "\u{f2e5}",
    "utensils": "\u{f2e7}",
    "vectorsquare": "\u{f5cb}",
    "venus": "\u{f221}",
    "venusdouble": "\u{f226}",
    "venusmars": "\u{f228}",
    "vest": "\u{e085}",
    "vestpatches": "\u{e086}",
    "vial": "\u{f492}",
    "vials": "\u{f493}",
    "video": "\u{f03d}",
    "videoslash": "\u{f4e2}",
    "vihara": "\u{f6a7}",
    "virus": "\u{e074}",
    "virusslash": "\u{e075}",
    "viruses": "\u{e076}",
    "voicemail": "\u{f897}",
    "volleyballball": "\u{f45f}",
    "volumedown": "\u{f027}",
    "volumemute": "\u{f6a9}",
    "volumeoff": "\u{f026}",
    "volumeup": "\u{f028}",
    "voteyea": "\u{f772}",
    "vrcardboard": "\u{f729}",
    "walking": "\u{f554}",
    "wallet": "\u{f555}",
    "warehouse": "\u{f494}",
    "water": "\u{f773}",
    "wavesquare": "\u{f83e}",
    "weight": "\u{f496}",
    "weighthanging": "\u{f5cd}",
    "wheelchair": "\u{f193}",
    "wifi": "\u{f1eb}",
    "wind": "\u{f72e}",
    "windowclose": "\u{f410}",
    "windowmaximize": "\u{f2d0}",
    "windowminimize": "\u{f2d1}",
    "windowrestore": "\u{f2d2}",
    "winebottle": "\u{f72f}",
    "wineglass": "\u{f4e3}",
    "wineglassalt": "\u{f5ce}",
    "wonsign": "\u{f159}",
    "wrench": "\u{f0ad}",
    "xray": "\u{f497}",
    "yensign": "\u{f157}",
    "yinyang": "\u{f6ad}",
]
